# Generated by Django 5.0.6 on 2024-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_img', models.ImageField(default=None, upload_to='image')),
                ('product_details', models.CharField(max_length=500)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.IntegerField(choices=[(0, 'ALL'), (1, 'VEGETABLES'), (2, 'FRUITS')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
