# Generated by Django 5.0.6 on 2024-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_checkout_alter_cart_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
