# Generated by Django 5.0.6 on 2024-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
