# Generated by Django 5.0.6 on 2024-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_reply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app1.product'),
            preserve_default=False,
        ),
    ]
