# Generated by Django 5.0.6 on 2024-06-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
