# Generated by Django 5.0.6 on 2024-06-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='product',
        ),
    ]
