# Generated by Django 5.0.6 on 2024-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.IntegerField(choices=[(0, 'ALL'), (1, 'Vegetables'), (2, 'Fruits')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
